version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redis
    versions:
    - 3.1.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: ioredis
    versions:
    - 4.24.3
    - 4.24.4
    - 4.24.5
    - 4.24.6
    - 4.25.0
    - 4.26.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.13.14
  - dependency-name: "@babel/register"
    versions:
    - 7.13.14
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
  - dependency-name: "@types/ioredis"
    versions:
    - 4.22.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
  - dependency-name: "@babel/node"
    versions:
    - 7.13.12
  - dependency-name: sequelize
    versions:
    - 6.5.0
    - 6.5.1
    - 6.6.1
  - dependency-name: googleapis
    versions:
    - 67.0.0
    - 67.1.0
    - 67.1.1
    - 68.0.0
  - dependency-name: "@types/jsonwebtoken"
    versions:
    - 8.5.1
  - dependency-name: koa-helmet
    versions:
    - 6.1.0
  - dependency-name: "@types/koa"
    versions:
    - 2.11.7
    - 2.11.8
    - 2.13.0
    - 2.13.1
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.13
    - 7.13.0
    - 7.13.8
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.168
